# A simple action usage
name: Build Kernel A71
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/crdroidandroid/android_kernel_samsung_a71
          kernel-dir: 
          kernel-branch: 16.0
          config: cas_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          ksu-other: yes
          ksu-url: https://github.com/SukiSU-Ultra/SukiSU-Ultra
          android-version: 16
          aosp-clang-version: r383902
          disable-lto: false
          anykernel3: true
          anykernel3-url: https://github.com/osm0sis/AnyKernel3
